name: Build GUI exe with Pyinstaller

on: [push]

jobs:
  build:
    strategy:
      matrix:
        app: ["client", "verification"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src/${{ matrix.app }}

    - uses: actions/upload-artifact@v2
      with:
        name: verification
        path: src/${{ matrix.app }}/dist/windows
        if-no-files-found: error
