name: Build GUI exe with Pyinstaller

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src/verification

    - uses: actions/upload-artifact@v2
      with:
        name: verification
        path: dist/windows
